lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    allow_no_expiration: true
    token_ttl: '%env(TOKEN_DURATION)%'
#    token_ttl: '%env(TOKEN_DURATION)%'
#    allow_no_expiration: true