monolog:
    handlers:
        main:
            type: fingers_crossed
            # 500 errors are logged at the critical level
            action_level: critical
            # to also log 400 level errors (but not 404's):
            # action_level: error
            # excluded_http_codes: [404]
            handler: deduplicated
        deduplicated:
            type: deduplication
            handler: symfony_mailer
        symfony_mailer:
            type: symfony_mailer
            from_email: 'Orange Simulator <noreply@afrikpay.com>'
            to_email:   ['willy.damtchou@afrikpay.com', 'a.noubissi@afrikpay.com', 't.njipmo@it.afrikpay.com', 'luc.tandoum@it.afrikpay.com', 'f.mansour@it.afrikpay.com']
            subject: 'Orange Simulator Bug! %%message%%'
            level: critical
            formatter: monolog.formatter.html
            content_type: text/html

        requestlog:
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%.request.log'
            level: INFO
            max_files: 3
            channels: [ request ]

        doctrinelog:
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%.database.log'
            level: DEBUG
            max_files: 3
            channels: [ doctrine ]

        errorlog:
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%.error.log'
            level: ERROR
            max_files: 3

        criticallog:
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%.critical.log'
            level: CRITICAL
            max_files: 3

        alertlog:
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%.alert.log'
            level: ALERT
            max_files: 3

        emergencylog:
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%.emergency.log'
            level: EMERGENCY
            max_files: 3