services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php2
    volumes:
      - .:/usr/src/app
    ports:
      - '8000:80'
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://orangeairtimesimulator:orangeairtimesimulator@symfony_mysql2:3306/orangeairtimesimulator?serverVersion=8.0&charset=utf8
    env_file:
      - .env
    user: 1000:1000
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: always
    container_name: symfony_mysql2
    environment:
      MYSQL_ROOT_PASSWORD: orangeairtimesimulator
      MYSQL_DATABASE: orangeairtimesimulator
      MYSQL_USER: orangeairtimesimulator
      MYSQL_PASSWORD: orangeairtimesimulator
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - '8086:8080'

  nginx:
    image: nginx:1.23.3-alpine
    restart: always
    volumes:
      - './public:/usr/src/app/public'
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '8087:80'
    depends_on:
      - php

volumes:
  mysql-data:
