services:
  php:  # Vérifie que c'est bien "php"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php
    volumes:
      - .:/var/www/html/
    ports:
      - '8000:80'
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://orangeairtimesimulator:orangeairtimesimulator@127.0.0.1:3306/orangeairtimesimulator?serverVersion=15&charset=utf8
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: on-failure
    container_name: symfony_mysql
    environment:
      MYSQL_ROOT_PASSWORD: orangeairtimesimulator
      MYSQL_DATABASE: orangeairtimesimulator
      MYSQL_USER: orangeairtimesimulator
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
        image: adminer
        restart: on-failure
        ports:
            - '8086:8080'


volumes:
  mysql-data:
